### ISSUE TITLE
KMI Status not hooked up?

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#142]
Right now the status for all of these on projects is "delayed" but in the backend, delayed isn't even an option which is why I'm guessing it is just fake data right now.

**Comment by dereklieu** [comment]
The status is calculated on the front-end using the formula I laid out in #129, once that's merged this will be fixed. Closing this as a dupe.

**Comment by dereklieu** [comment]
Oops my mistake, this is different from #129. 

Looks like everything coming from the back-end is "Partially Implemented - تحقق جزئياً". 

I'm not sure we should be sending arabic and english text here, since we need to infer the right class name to use based on the status, and having arabic in that text will complicate that. 

@felskia what are the possible options for this field?

**Comment by felskia** [comment]
@dereklieu this has nothing to do with the actual project status. The backend user fills it in separately for each. It's either: 

- Not Implemented
- Partially Implemented 
- Implemented
