### ISSUE TITLE
Be able to drop projects from the map

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#168]
On the projects and indicators page, when you click on the "Add and Filter Projects" button there is a checkbox to turn off projects. Currently this doesn't work.

**Comment by nbumbarger** [comment]
@felskia I don't think this interaction makes sense, as is. In essence, checking this box has the effect of selecting all the other boxes, and unchecking it has the effect of deselecting all the other boxes. That means that there are two, independent ways of selecting/ deselecting all, which can overlap in unexpected. Instead of a checkbox, this should be a button to select all/ deselect all which updates the state of the other buttons.

**Comment by felskia** [comment]
@nbumbarger I totally agree. I feel like the checkbox at the top should be just for turning the projects on the map on or off and not be affected by the other filter checkboxes in the modal. That's what you're saying, right?

**Comment by nbumbarger** [comment]
Hmm, that's an option. But what I was saying is that it should be a button to select or deselect all the other checkboxes. If it turns projects off independently without affecting the rest of the form, then you have two independent ways to toggle global project visibility, which is clunky from a programming perspective.

**Comment by felskia** [comment]
@nbumbarger yeah, maybe if projects are unchecked or turned off that means that the filter form is greyed out in some way and can't be used.
