### ISSUE TITLE
Responsible Ministry 

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#192]
The text for this isn't showing up on the arabic side @nbumbarger 

Also the CSS seems a little broken here @ascalamogna

**Comment by nbumbarger** [comment]
This data is currently missing for most of the ministries

**Comment by felskia** [comment]
@nbumbarger why did you put won't fix on this one? The arabic side of this... the timelines aren't even showing up. I feel like we use these styles elsewhere. https://map-egypt.github.io/#/ar/ministry/ministry-2?_k=no0w4d

<img width="1141" alt="screen shot 2017-01-19 at 5 04 23 pm" src="https://cloud.githubusercontent.com/assets/5421566/22127318/72ae979e-de69-11e6-9dc3-a6dc7c8c8be9.png">
<img width="1165" alt="screen shot 2017-01-19 at 5 04 28 pm" src="https://cloud.githubusercontent.com/assets/5421566/22127319/72b26fae-de69-11e6-9202-eb9ff942fe45.png">

**Comment by nbumbarger** [comment]
My understanding was that this issue originally referred to the responsible ministry item shown in the project page, which we don't have for most projects and isn't in the API.

**Comment by felskia** [comment]
True, but we have a page for it because we have a fake ministry in there now. Either way, the page doesn't work for some reason in Arabic. Could one of you take a look?

**Comment by ascalamogna** [comment]
@felskia is this for ministry 2? Can you point to the exact page here, because I don't quite get this when I look at some.

**Comment by felskia** [comment]
Yeah, it's this page: https://map-egypt.github.io/#/ar/ministry/ministry-2?_k=no0w4d 

I just cleared all browsing history etc... and it's still like it's shown in the screenshots for me

**Comment by ascalamogna** [comment]
this works for me locally sometimes and not others. These are the errors I get 
<img width="788" alt="screen shot 2017-01-19 at 5 31 25 pm" src="https://cloud.githubusercontent.com/assets/6752098/22128146/3bcc14a0-de6d-11e6-913d-9e5f151ddc99.png">

**Comment by felskia** [comment]
I get this: 
<img width="1168" alt="screen shot 2017-01-19 at 5 39 18 pm" src="https://cloud.githubusercontent.com/assets/5421566/22128391/502e7b3a-de6e-11e6-972b-6118deba4650.png">

**Comment by nbumbarger** [comment]
@felskia The primary issue here relates back to our not having the Arabic ministry names. The Arabic map will work fine as soon as those names are dropped into the database. What's happening is the component searches for the indicated ministry's projects, and can't find anything because the Arabic ministry name is blank. This crashes the map because it attempts to fit an empty geometry. When you switch over to English, the search is done using the English names, which stay in the map when you switch back.

The secondary issue is that the graph is being inserted into a smaller space in the Arabic version, but it only resizes when the window size is changed so it ends up too large for the space (until the window is moved). I should be able to fix this by reversing the grid layout to maintain the proportions used for the map and graph.

**Comment by felskia** [comment]
@nbumbarger Why does it happen on this page vs. all the others then? For the rest of the site, it just takes on the English text if there isn't arabic. Also what about the timelines?

**Comment by nbumbarger** [comment]
This is a dynamic endpoint which queries for the ministry name shown in the URL. So it's searching for projects that have `ministry-2` as an Arabic `responsible-ministry` attribute, but it can't find anything because all the Arabic ministry names are blank in the database.
We can solve this temporarily by adding placeholder ministry names to the database (ministry-2 would be fine for this, or it could be something different to test that it's really working).
