### ISSUE TITLE
Map pins need to reflect districts instead of governorates

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#249]
When districts are known pins should map to those districts.

**Comment by nbumbarger** [comment]
@kamicut @dereklieu Could either of you estimate how difficult this feature would be, and explain the geographic data structure a bit? I never looked into what the points in the geographic data represent or how they're related to projects.

For example, if I have a list of projects, what attribute would I use from each to query (by attribute or intersection) for the associated district geography, and which dataset contains the district geometry? Could I use district IDs from the individual projects' `location` attribute to select data from somewhere (I don't see spatial data for districts at the `geography` endpoint). Are the points necessary to accomplish this issue already attached to the individual projects, in the `location/markers` attribute?

**Comment by dereklieu** [comment]
District topojson files are now being fetched on startup, so they're available without you needing to do anything else - [link](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/main.js#L47).

If you want to peek at the parsed geojson structure you can console `features` - [link](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/actions/index.js#L109).

Once we get the districts we do some normalization on the id's. This gets saved at `state.geography.districts` - [link](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/reducers/api.js#L40).

The [`getProjectCentroids`] function is where you pass a list of projects and the `features` array of a typical geojson data structure, and in return get a list of markers - [link](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/utils/map-utils.js#L10-L47). 

As you can see, that function is where a few assumptions are hard-coded. [This line](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/utils/map-utils.js#L22) for example should look at whether there's a district-level identifier in addition to governorate. 

How I would approach this:

1. In all the places where it's called, pass the entire `state.geometry` object into  `getProjectCentroids` instead of [just the governorates.](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/views/project-browse.js#L515)
2. [Aggregate the regions](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/utils/map-utils.js#L16-L27) like how we do it now, except make it aware of whether the region is a district or governorate, then save that piece of information (whether the region is district or governorate) somehow.
3. Now instead of just grabbing the [governorate](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/utils/map-utils.js#L30-L31) decide whether to grab the appropriate governorate **or** district geojson object based on that information you saved. You may or may not need to create a district id mapping, as that data may already be in the geojson.

The rest of the code should pretty much just work. I'd estimate this to take no more than a day.

**Comment by nbumbarger** [comment]
thanks @dereklieu, I'll let you know if I have questions
