### ISSUE TITLE
CSV download issues

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#274]
It just takes you to a page with all of the data. Is there a way to trigger this? 

Also, Hagar is having a problem downloading this from Chrome. She says: " I use google chrome, I get a download file and I try to open with Excel, it asks again if I want to open this file, when I click ok nothing happens (I attached some screenshots)." 

Screenshots: https://www.dropbox.com/sh/v6cch9ix398uf48/AADLnDENlQcHjOhu-M_fhl2ca?dl=0

@nbumbarger let me know if you could fix in the next day or two.

**Comment by nbumbarger** [comment]
@felskia From what I can see, the data does automatically download in Safari- it's just that it also opens in a new tab. This behavior would be hard to change- the hack I found results in the string `data:text/csv;charset=utf-8` being appended to the start of the CSV, which I think is less desirable than simply needing to close the new tab.

**Comment by felskia** [comment]
@nbumbarger it opens in a new tab but never downloads it. I just tried it again on my machine and it didn't do anything. 

Also what about the other issue?

**Comment by nbumbarger** [comment]
I can't recreate in the current version of Safari. It definately isn't downloading, and isn't being caught by any extensions? Does changing line 57 of `components/csv-btn.js` from `window.open(encodedUri);` to `window.open(encodedUri, '_blank')` help?

Hagan is having trouble recognizing the file because it was saved without the .csv extension. You can't associate extensionless files with specific applications.

I have a hacky solution that should ensure Windows attaches the csv extension to files, but it will still show the file contents in Safari (it downloads the contents as well, which is the existing behavior on my computer).

**Comment by nbumbarger** [comment]
@felskia can check whether this branch improves things https://github.com/map-egypt/map-egypt.github.io/pull/280?

**Comment by felskia** [comment]
@nbumbarger yeah, in safari it downloads the file now. Thanks!
