### ISSUE TITLE
Arabic text - not showing up

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#284]
There are three issues on the arabic side. 

Text not showing up in Arabic or links not working
- This is an example: https://map-egypt.github.io/#/en/projects/13f7fd00-a53f-4566-a771-f9de5f73fc81?_k=u3v3uy. I believe the local manager is the missing one
- The link for the ministry isn't working on the arabic side

Also, if there is no Arabic text, there should instead just be English. I'll check to see if it's happening on other pages. 

Finally, if you're in Arabic and click to a donor page, the graph doesn't show up below the big stat numbers. If you click to English and then press refresh it does. 

@dereklieu @nbumbarger anyone have time to fix this bug tomorrow?

**Comment by nbumbarger** [comment]
@felskia Local manager and ministry are typically blank records (they come from the database, not the translation file). We can make them default to English when Arabic is unavailable.

**Comment by dereklieu** [comment]
Seems like default to English when Arabic isn't available is a little heavy-handed.. at worst, it could make someone a little less knowledgeable think the translation was broken and serving English, when it was in fact just missing.

Shouldn't the task of getting the Arabic in place for the entire site be on them at this point? We've built all the tools for them to do that.

**Comment by felskia** [comment]
@nbumbarger @dereklieu so, it's that way throughout the whole site, so I don't understand why it's different. Isn't more data better than none? Also, yes, they're trying to put in the arabic text and this is why it was pointed out. Apparently Hagar was trying to input Arabic text for projects and it wasn't showing up. 

But please also look at the other issues on this ticket that don't involve including English but are bugs.

**Comment by dereklieu** [comment]
1. local manager not showing up: yes, it's because they haven't put in arabic text for local manager.
2. ministry links aren't working, those should have used english titles in the link and not arabic, that's a bug I can fix now.
3. I can look at the chart not showing up.

The projects all have English names now because none of them had Arabic names when we built this :)

We did that so we could show them a site that didn't look broken when switching to Arabic. It wasn't the right way, but we were under time crunch, so we made a feature that does the opposite of what you'd expect. When you ask for Arabic, you'd expect Arabic.

Making the site show English if there's no Arabic would take me an hour or two, but I'm opposed to doing this because it seems like another feature that doesn't do what you'd expect. Why should the site show English if you're asking for Arabic? Ultimately it gives the admins a pass at the expense of the user.

Let's fix the site to show Arabic when you're asking for Arabic, English when you're asking for English.
