### ISSUE TITLE
Implement Download Button

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#70]
Make a pdf of the page minus the header and the footer.

**Comment by dereklieu** [comment]
Generating a PDF with all of the different elements (text, charts, map) is not feasible given the timeline. Can we cut this requirement? In Chrome, you can save as a pdf by using the print interface, and in the past we've solved this by making a print stylesheet so that the output looks tolerable.

**Comment by dereklieu** [comment]
@felskia Have we decided whether to remove this completely, or what we want to come out of this button?

**Comment by felskia** [comment]
@dereklieu Could we have a print or print to PDF button?

**Comment by dereklieu** [comment]
We can make it a print button, but they would have to do the print to pdf process themselves.

**Comment by felskia** [comment]
@nbumbarger I say that we just implement this as "Print to PDF". Change the language and then open up a print screen. 

My only question is, we need to make a style sheet for this, yes? How hard is it. Sites just seem to suggest that it's a different style sheet: http://www.creativebloq.com/responsive-web-design/make-your-website-printable-css-3132929. Is this something @ascalamogna can put together?

**Comment by ascalamogna** [comment]
@felskia when does the styling need to be done? I'm worried this might take me an eggroll, so I'd have to finish it up tomorrow sometime. I

**Comment by felskia** [comment]
@ascalamogna totally fine. We have all day tomorrow. What I think it that we just want printable pages. So no header and footer.

**Comment by dereklieu** [comment]
I've done these before. I've found the easiest way is to just write everything out in `_print.scss` (make sure to require it at the end of the `main` file so it overwrites everything above it) and just hide and move everything around as needed - much of the work will hopefully already be done by media queries assuming mobile size. Once you have it looking right, then wrap it in a print media query and maybe do a test print to pdf to confirm.

Things that may not look right immediately are map markers, since when you apply the print media query, it does not cause the map to re-center (it just shrinks it usually). What you can end up with is a map that appears off-center. One possibility is to trigger a re-center of the map when someone invokes the print button.

The charts and other content should respond better to the change of dimensions.

**Comment by ascalamogna** [comment]
okay I'll set up a print style sheet

**Comment by nbumbarger** [comment]
Yes, you can specify a print stylesheet. Right now the site doesn't look great as a PDF. Certain CSS properties like background color don't print by default, and it looks like elements that rely on the column grid are defaulting to full-width. This makes the cards in the list view full-width, and makes the indicator selectors and graph both full width, which bumps down the graph. There's also some whitespace issues at the top of the page

I think that a lot of this can be solved in the print stylesheet by hiding all interface elements. There's no need for the header navigation, indicator selectors, or any of the other buttons. I would start by hiding those elements, and then see what's left to clean up.

**Comment by felskia** [comment]
Hook up buttons is what is left
